# Generated by Django 5.0.7 on 2024-07-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
